# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(127, 182, 261, 281))
        self.textEdit.setObjectName("textEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(280, 70, 111, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.Port_Label = QtWidgets.QLabel(self.centralwidget)
        self.Port_Label.setGeometry(QtCore.QRect(130, 70, 141, 16))
        self.Port_Label.setObjectName("Port_Label")
        self.baslat_button = QtWidgets.QPushButton(self.centralwidget)
        self.baslat_button.setGeometry(QtCore.QRect(130, 110, 121, 32))
        self.baslat_button.setObjectName("baslat_button")
        self.durdur_button = QtWidgets.QPushButton(self.centralwidget)
        self.durdur_button.setGeometry(QtCore.QRect(260, 110, 131, 32))
        self.durdur_button.setObjectName("durdur_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 160, 60, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 43))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Port_Label.setText(_translate("MainWindow", "Port Numarasını Giriniz:"))
        self.baslat_button.setText(_translate("MainWindow", "Başlat"))
        self.durdur_button.setText(_translate("MainWindow", "Durdur"))
        self.label.setText(_translate("MainWindow", "Sensör"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
